import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans, Poppins } from "next/font/google";
import "./globals.css";
import AosProvider from "@/providers/aos";
import Header from "@/components/header";
import Footer from "@/components/footer";


const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Ouverture RDC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <AosProvider>
        <body className={poppins.className}>
          <Header />
          {children}
          <Footer />
          </body>
      </AosProvider>

    </html>
  );
}
