import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import AosProvider from "@/providers/aos";
import Header from "@/components/header";


const inter = Inter({ subsets: ["latin"] });
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Ouverture RDC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <AosProvider>
        <body className={ibmPlexSans.className}>
          <Header />
          {children}</body>
      </AosProvider>

    </html>
  );
}
